initial_soc: 0.5
capacity: 10
size_hours: 1
charge_efficiency: 0.9
discharge_efficiency: 0.9
time_step: 0.25
N_timesteps: 32
N_trading_timesteps: 32
N_daily_cycles_max: 2
N_SOC_levels: 100
N_price_paths: 10000
basis_functions_type: "Laguerre"
N_basis_functions: 6